from __future__ import annotations

import os
from typing import Any

from src.agent.llm_client import call_openai_compatible_json, get_llm_settings


MEMORY_CANDIDATE_SYSTEM_PROMPT = """
You generate long-term memory candidates for a memory-driven NPC agent.

You do not write to the database. You only propose candidates.

Return one JSON object:
{
  "candidates": [
    {
      "should_write": true,
      "memory_type": "player_profile|preference|relationship|event|quest",
      "content": "short factual memory in English",
      "importance": 1,
      "confidence": 0.0,
      "tags": ["short_tag"],
      "evidence_text": "exact quote from player_input, npc_response, tool calls, or state_changes",
      "reason": "short reason"
    }
  ]
}

Rules:
- Use player_profile for stable player self-description, emotional state, needs, or personal situation.
- Use preference only for stable communication or gameplay preferences directly stated by the player.
- Use event only for concrete events supported by tool calls or world event records.
- Use quest only for quest progress supported by quest state changes.
- Use relationship only for selected-NPC/player relationship changes supported by state_changes.
- Do not turn "the player needs help" into "the player helped an NPC".
- evidence_text must be an exact quote or exact serialized evidence fragment from the current turn.
- If nothing is worth long-term memory, return an empty candidates array.
"""


def memory_llm_enabled() -> bool:
    settings = get_llm_settings()
    if settings.provider != "openai_compatible" or not settings.api_key:
        return False
    return os.environ.get("AGENT_NPC_MEMORY_LLM_ENABLED", "1").strip() not in {"0", "false", "False"}


def generate_memory_candidates(
    policy_input: Any,
    rule_candidates: list[dict[str, Any]],
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    if not memory_llm_enabled():
        return [], {"enabled": False, "stage": "candidate_generation", "reason": "Memory LLM disabled or not configured."}

    payload = {
        "player_input": policy_input.player_input,
        "npc_response": policy_input.npc_response,
        "recent_short_term_context": policy_input.recent_short_term_context,
        "retrieved_lore": policy_input.retrieved_lore,
        "retrieved_long_term_memories": policy_input.retrieved_long_term_memories,
        "state_before": {
            "npc": policy_input.npc_before,
            "player": policy_input.player_before,
            "quest": policy_input.quest_before,
        },
        "state_after": {
            "npc": policy_input.npc_after,
            "player": policy_input.player_after,
            "quest": policy_input.quest_after,
        },
        "tool_calls": policy_input.tool_calls,
        "state_changes": policy_input.state_changes,
        "rule_candidates": rule_candidates,
        "allowed_memory_types": ["quest", "event", "relationship", "preference", "player_profile"],
    }
    try:
        response = call_openai_compatible_json(
            system_prompt=MEMORY_CANDIDATE_SYSTEM_PROMPT,
            user_payload=payload,
        )
    except Exception as exc:
        return [], {
            "enabled": True,
            "stage": "candidate_generation",
            "status": "error",
            "reason": str(exc),
        }

    raw_candidates = response.get("candidates", [])
    candidates = []
    for candidate in raw_candidates if isinstance(raw_candidates, list) else []:
        normalized = normalize_llm_candidate(candidate)
        if normalized is not None:
            candidates.append(normalized)
    return candidates, {
        "enabled": True,
        "stage": "candidate_generation",
        "status": "ok",
        "candidate_count": len(candidates),
    }


def normalize_llm_candidate(candidate: Any) -> dict[str, Any] | None:
    if not isinstance(candidate, dict):
        return None
    tags = candidate.get("tags", [])
    if not isinstance(tags, list):
        tags = []
    return {
        "should_write": bool(candidate.get("should_write", False)),
        "npc_id": "lina",
        "content": str(candidate.get("content", "")).strip(),
        "memory_type": str(candidate.get("memory_type", "event")).strip(),
        "importance": clamp_int(candidate.get("importance", 5), 1, 10),
        "tags": [str(tag).strip() for tag in tags if str(tag).strip()],
        "confidence": clamp_float(candidate.get("confidence", 0.7), 0.0, 1.0),
        "reason": str(candidate.get("reason", "Generated by memory candidate LLM.")).strip(),
        "evidence_text": str(candidate.get("evidence_text", "")).strip(),
        "source": "llm_candidate",
    }


def clamp_int(value: Any, lower: int, upper: int) -> int:
    try:
        return max(lower, min(upper, int(value)))
    except (TypeError, ValueError):
        return lower


def clamp_float(value: Any, lower: float, upper: float) -> float:
    try:
        return max(lower, min(upper, float(value)))
    except (TypeError, ValueError):
        return lower
